### ISSUE TITLE
PieChart is shifted due to labels

### ISSUE THREAD

**Issue by VitalyPeryatin** [KoalaPlot/koalaplot-core#12]
PieChart is shifted (not horizontally centred) when labels width from one sight much more than labels width from another one. 

<img width="307" alt="image" src="https://github.com/KoalaPlot/koalaplot-core/assets/22561563/866d0b01-ee44-4a4d-99ba-1a3c0676158d">

**Comment by gsteckman** [comment]
I just pushed 0.4.0-dev1 which added a flag to PieChart that forces the pie to be in the center. This will center it both horizontally and vertically. The consequence is that the pie will be made smaller to accommodate the empty space that will be present on one side, which is why I made it an option.
