### ISSUE TITLE
Crash with intrinsic measurements

### ISSUE THREAD

**Issue by garretyoder** [KoalaPlot/koalaplot-core#19]
I'm assuming inside the chart library you use Subcompose? Is there a recommended way to use the charts inside of a widget that grows to match its parent? (Flow layouts, lists, etc).

Using it inside a flow layout produces the following:

java.lang.IllegalStateException: Asking for intrinsic measurements of SubcomposeLayout layouts is not supported. This includes components that are built on top of SubcomposeLayout, such as lazy lists, BoxWithConstraints, TabRow, etc

**Comment by gsteckman** [comment]
Yes, they use SubcomposeLayout. This is a limitation in Compose. In the case of PieChart, it looks possible to use Layout instead of SubcomposeLayout, but for the other chart types, it won't be so easy. One workaround might be to put the chart in a Box and set it to a fixed size with a Modifier. But fixing the size of things comes with its own issues.
