### ISSUE TITLE
Limit the display of labels if there is no space for labels for pie chart.

### ISSUE THREAD

**Issue by Monabr** [KoalaPlot/koalaplot-core#34]
Hello.

I get poor display when there are a lot of pieces of the pie and not enough space to display the labels. For example, 40%, 40% and 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1% , 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%, 1%,

![image](https://github.com/KoalaPlot/koalaplot-core/assets/30532666/493d1210-584f-4f60-a72f-705ac7d31386)

**Comment by gsteckman** [comment]
A best practice for pie charts in this situation is to aggregate many smaller items into an "other" category. Many slices with 1% value are going to be indistinguishable. You could choose, for example, to aggregate everything smaller than the top 7 items, or to additionally aggregate items below a specific size threshold, e.g., 3%.

Alternatively, you can provide your own implementation for the label and labelConnector Composables (these are parameters to the PieChart function), and choose not to draw any content for specific values. So I think the hooks are in place to allow you to control which labels are/aren't displayed.

The reason the logic isn't implemented into the library is because users may want to implement their own algorithm for these decisions. If there are well-known approaches for doing this that are popular or implemented in many other graphing packages, then that would be something I would consider putting into a wrapper function or DSL as a convenience.
