### ISSUE TITLE
`publishToMavenLocal` on a Mac only publishes iOS artifacts

### ISSUE THREAD

**Issue by sunny-chung** [KoalaPlot/koalaplot-core#45]
`publishToMavenLocal` on a Mac only publishes iOS artifacts. I expect there are other artifacts like common or jvm.

**Comment by gsteckman** [comment]
Yes, this is intentional so that when releasing via git actions it doesn't publish the non-Apple artifacts to Maven Central twice. But I can see how this could be inconvenient if you are developing on a Mac. Within the convention-plugins folder hierarchy, there is a file convention.publication.gradle.kts which suppresses publishing non-iOS artifacts when running on Mac. If you comment out the block under the comment "// When on MacOS, only publish ios artifacts" (line 42), it should publish everything. I don't have a Mac so it's very difficult for me, essentially impossible, to troubleshoot build issues or iteratively try changing things that would happen in a Mac environment. Ideally, local publishing would build everything regardless of the host platform, but when publishing to Maven Central on a Mac host only the iOS artifacts would be published. It would be great if this is something you could figure out how to get working if you have a Mac.

**Comment by sunny-chung** [comment]
In the conditions, you could add checking for environment variables or Gradle command arguments, and injecting those arguments into Github actions. In this way you could avoid publishing non-Apple artifacts only if it is executed by Github actions.

**Comment by gsteckman** [comment]
There may be another way without having to change the actions configuration. In the condition

`(isMac && name.contains("ios", ignoreCase = true)) || !isMac`

add a clause to always publish if it is a ToMavenLocal publication, like this:

`(isMac && name.contains("ios", ignoreCase = true)) || !isMac || name.endsWith("ToMavenLocal")`

Can you try that and let me know if it works?

**Comment by sunny-chung** [comment]
It works.
