### ISSUE TITLE
Add ios target for using library with Compose for iOS

### ISSUE THREAD

**Issue by VitalyPeryatin** [KoalaPlot/koalaplot-core#6]
Add ios target for using library with Compose for iOS. It is impossible to use these dependencies in project with Compose for iOS without this target:
- koalaplot-core
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/22561563/209458896-99cda6c3-b97c-4f3b-a04f-cab436f87c7f.png">

**Comment by gsteckman** [comment]
Hi, I've added the ios() target and updated the GitHub actions to build on MacOS. However, there is a build error. Unfortunately, I don't have a Mac so I cannot troubleshoot the problem locally, and it took the runner almost 10 minutes to get to the point where a missing symbol was found.

If you have a Mac, could you help find the problem?

[Link to the build log with the error](https://github.com/KoalaPlot/koalaplot-core/actions/runs/5231188090/jobs/9445175743)

**Comment by maltsev-gorskij** [comment]
Hi again @gsteckman !
Also see this issue https://github.com/JetBrains/compose-multiplatform/issues/2342

Please try to add 
`kotlin.native.cacheKind=none`
in your gradle.properties and try building project with ios() source set

**Comment by gsteckman** [comment]
I merged the PR from @jakepurple13 which includes the cacheKind property. But the builds are still failing due to undefined symbols during linking. There are a lot of warnings of mismatched versions for the simulator, which may be the root cause of the undefined symbols. The odd thing is in the latest commit I removed the iosSimulatorArm64() target, but it is still causing errors, [see log](https://github.com/KoalaPlot/koalaplot-core/actions/runs/5299374535/jobs/9592289796) for version 11 vs version 9.

When I left iosSomulatorArm64() in, it was version 15.2 vs version 9 - [see log](https://github.com/KoalaPlot/koalaplot-core/actions/runs/5299223656/jobs/9592060022).

Any ideas where these version numbers are coming from? I tried searching and looked at some of the Kotlin multiplatform examples, but didn't see any ios specific version information in the build files.

**Comment by maltsev-gorskij** [comment]
Hello again @gsteckman. I'v created PR with fixes, which helped me to assemble all library artifacts and sucessfully use your library in compose multiplatform https://github.com/KoalaPlot/koalaplot-core/pull/16

**Comment by zacharee** [comment]
Is there a way to get a snapshot build of the repo? JitPack doesn't seem to work anymore.

**Comment by maltsev-gorskij** [comment]
> Is there a way to get a snapshot build of the repo? JitPack doesn't seem to work anymore.

Hi @zacharee. 

I'm still waiting for @gsteckman to publish a new release with latest fixes. 
For now i'm publishing Koalaplot artifacts to mavenLocal() with publishToMavenLocal gradle task and building my project this way.

**Comment by gsteckman** [comment]
Hi @zacharee, I published a 0.4.0-dev1 build with ios artifacts. Please let me know if they don't work ok for you. I don't own any Apple devices so can't test them. Thanks to @maltsev-gorskij for helping to get the ios build working.

**Comment by zacharee** [comment]
I tried it, but it doesn't look like iOS artifacts got generated/uploaded. Gradle fails to sync because it can't find the ones for iOS.

**Comment by gsteckman** [comment]
I see them in search results at https://central.sonatype.com/search?q=koalaplot, and also can see the files at https://repo1.maven.org/maven2/io/github/koalaplot/. 

What is the specific error you are getting?

**Comment by zacharee** [comment]
I tried again and it's syncing now ¯\\_(ツ)_/¯. I'll open a new issue if there are problems with functionality on iOS.

**Comment by maltsev-gorskij** [comment]
> Hi @zacharee, I published a 0.4.0-dev1 build with ios artifacts. Please let me know if they don't work ok for you. I don't own any Apple devices so can't test them. Thanks to @maltsev-gorskij for helping to get the ios build working.

No problems. Glad to help ;)

P.S. Thanks for release!

**Comment by joreilly** [comment]
Tried out the iOS support and works great....thanks!

https://twitter.com/joreilly/status/1699444224184201703?s=20
