### ISSUE TITLE
Automatic axis scaling for incoming data

### ISSUE THREAD

**Issue by SPC-code** [KoalaPlot/koalaplot-core#63]
Currently it is not possible to automatically re-scale axis to match data change in case of dynamic data. It would be nice to have this option in Axis API.

**Comment by gsteckman** [comment]
I am not sure what you mean, this is already possible. I added a [sample](https://github.com/KoalaPlot/koalaplot-samples/blob/main/src/commonMain/kotlin/io/github/koalaplot/sample/TimeAxisLineChart.kt) that will rescale an axis with changing data.

Is there a more efficient way to do this?

**Comment by gsteckman** [comment]
Maybe I misinterpreted your initial ask. I thought it was about getting the plot to rescale the axes when the axis range changes. But this works using the normal Compose way of doing things, e.g. with MutableState. Are you instead asking for algorithms to be implemented to calculate what the min..max range should be based on provided data? In this case I don't see the relevance of a callback function. 

I haven't implemented autorange scaling because I haven't found a reliable algorithm to do it. If anyone can point me to one, I don't expect it to be difficult to implement.

**Comment by gsteckman** [comment]
A callback won't cause recomposition if the scale changes but the data doesn't change. I'd need to be convinced that creating an axis object is a performance bottleneck to move away from an approach that is aligned with the rest of the Compose APIs (I can't think of a Compose API that uses a callback to access data).

Autorange isn't necessarily quite so simple, because people may want to round the range up/down to the nearest "major" interval, like a factor of 10. For example, if your data min/max is -3 and 92, would you want an axis exactly starting and stopping at -3 and 92, or starting at -10 and stopping at 100? This is possible to do, and the FloatLinearAxisModel has some code like this to generate the major ticks based on divisions of powers of 10. An axis builder with a configurable auto ranger would be a good thing for someone to contribute because it doesn't get into the inner workings of the plotting code.
