### ISSUE TITLE
Crash on FloatLinearAxisModel

### ISSUE THREAD

**Issue by vcoolish** [KoalaPlot/koalaplot-core#70]
Axis range end (${range.endInclusive}) must be greater than start (${range.start})

Why axis range cannot be stable line without changes? It causes crash for such cases

**Comment by gsteckman** [comment]
Are you trying to set the start and end to the same value?

**Comment by vcoolish** [comment]
I use it for y axis and it some times can be stale like array of [50, 50 ..., 50]
```
yAxisModel = remember(info.yRange) {
                FloatLinearAxisModel(
                    range = info.yRange,
                    minimumMajorTickSpacing = 50.dp,
                )
},
```

**Comment by gsteckman** [comment]
Then you need to artificially create a min/max range that has a non-zero difference, e.g. use an axis range that is +/- 10% of the value. Otherwise it is mathematically undefined where to place the point with a value of 50, e.g., should it go at the bottom, middle, or top of the axis, or somewhere else?

Also have a look at using `fun List<Float>.autoScaleRange(): ClosedFloatingPointRange<Float>` which takes care of situations like this for you.

**Comment by vcoolish** [comment]
> .autoScaleRange()

ok thanks!
