### ISSUE TITLE
Build failed on IOS

### ISSUE THREAD

**Issue by mjovanovic9999** [KoalaPlot/koalaplot-core#77]
When building demo example on iOS target, build fails.

Kotlin version 2.0.0
KoalaPlot version 0.6.2

**Comment by gsteckman** [comment]
I don't have any Apple devices, so have a limited ability to help here, but please elaborate on what you are doing and what the failure is. Are you trying to build the [samples](https://github.com/KoalaPlot/koalaplot-samples), or something else? What is the failure that you get?

**Comment by mjovanovic9999** [comment]
I was running demo samples from docs.

This is the build error:
![error](https://github.com/user-attachments/assets/7571747a-7c4e-44ff-b1b8-e87639ba47a7)

The build error persists on v0.6.3, but version v0.6.1 works well.

**Comment by gsteckman** [comment]
0.6.1 used Kotlin 1.9.22 and starting with 0.6.2 it uses Kotlin 2.0. Do you mind trying a local build with 0.6.3 but Kotlin 1.9.22 and see if that solves the build issue? If so I will revert the 0.6.x line to using Kotlin 1.9.22.

Zooming doesn't work on Desktop or Browser either. The way Compose handles mouse gestures is not uniform across platforms, and that probably applies to ios as well.

**Comment by mjovanovic9999** [comment]
[@AleksaStancev](https://github.com/AleksaStancev) can you elaborate further?

**Comment by gsteckman** [comment]
First, I think it would be good if you check if Kotlin 2.0.0 requires any different settings than with older kotlin versions in order to build correctly for ios. I don't know if that might be the real cause of the issue here and not the actual version itself or some interaction with something else in koalaplot-core. I expect that JetBrains would have extensively validated kotlin 2.0.0 with ios builds before releasing it.

Also since the examples for the documentation and the koalaplot-samples repository don't produce ios builds, you might want to post here what build configuration you are using and maybe someone who has experience with ios builds can help spot any  issues.

To build with a different kotlin dependency version, you'll need to clone the 0.6.1 branch of koalaplot-core, modify the kotlin dependency to 1.9.22 in the libs.versions.toml file, update the version of the build in build.gradle.kts to something custom, and build it to your local maven repository using `./gradlew publishToMavenLocal`. Then in your test code reference the custom version you used for koalaplot-core, so it uses the version you just built to maven local and not a version published on maven central.

**Comment by ryanw-mobile** [comment]
I have encountered the same issues on XCode/iOS and have then rolled back to 0.6.1.
However, after updating to Kotlin 2.0.10 yesterday, KoalaPlot 0.6.3 works without changing anything else.

@mjovanovic9999 , can you also try to update the Kotlin version?

**Comment by AleksaStancev** [comment]
@ryanw-mobile It worked after updating the Kotlin version. Thanks!

**Comment by mjovanovic9999** [comment]
[heart]         Milos Jovanovic reacted to your message:
________________________________

**Comment by MrJohn10** [comment]
Also experienced the crash with kotlin 2.0 and KoalaPlot version 0.6.3
I will try later with kotlin 2.10.
Maybe we could update readme/release notes to notify users about supported kotlin versions @gsteckman

**Comment by gsteckman** [comment]
0.6.3 was built with Kotlin 2.0.0 and I haven't had any reports of problems on Android, Desktop, or web. This appears to be an iOS only issue with Kotlin 2.0.0, not KoalaPlot specifically. The 0.7.x (main branch) is using Kotlin 2.0.20 but you'd have to build that from source as a release hasn't been made yet.
